name: PR:4.x U20

on:
  pull_request:
    branches:
      - 4.x

env:
  REPO: ${{ github.event.pull_request.head.repo.full_name }}

jobs:
  BuildAndTest:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    container:
      image: quay.io/asenyaev/opencv-ubuntu:20.04
    steps:
    - name: PR info
      run: |
        echo "$REPO"
